---
ID: "dd662ec9-b84a-45ad-a91c-befdc5730e37"
Parent: "9223eab8-87d6-4179-87da-e9f032b611e5"
Template: "dd22f1b3-bd87-4db2-9e7d-f7a496888d43"
Path: /sitecore/system/Modules/PowerShell/Script Library/SPE/Samples/DevOps/Web API/PublishAllSmart
DB: master
SharedFields:
- ID: "b1a94ff0-6897-47c0-9c51-aa6acb80b1f0"
  Hint: Script
  Value: |
    if ($HttpContext){
        $HttpContext.Response.ContentType = "application/json";
    }
    
    Get-Item -Path master:\content | Publish-Item -Recurse -PublishMode Smart 
    
    @{ "status" = "publishing started" } | ConvertTo-Json
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190827T110658Z
